name: Django
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

jobs:
  pytest:
    name: Test Django
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: data_power
          POSTGRES_PASSWORD: security_is_important
          POSTGRES_DB: data_power
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          pip install pipenv
          pipenv install --dev
      - name: Run Tests
        run: make test
        env:
          DATABASE_URL: postgres://data_power:security_is_important@localhost/data_power

  check-django-configuration:
    name: Check Django Configuration
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup
        run: |
          pip install pipenv
          pipenv install
      - name: Test Django Configured Correctly
        run: make check-django
        env:
          DATABASE_URL: sqlite:///db.sqlite3
          SECRET_KEY: Some very long and complex string which is very, very secure.
          CANONICAL_HOST: .net
